export TERM="xterm-256color"
export LANG="en_US.UTF-8"

export HISTFILE=~/.histfile
export HISTSIZE=1000
export SAVEHIST=1000

export ZPLUG_HOME=/opt/homebrew/opt/zplug

export PATH=${PATH}:/usr/local/sbin
export PATH=${PATH}:${HOME}/.bin
export PATH=${PATH}:${HOME}/.local/bin
export PATH=${PATH}:${ANDROID_HOME}/tools
export PATH=${PATH}:${ANDROID_HOME}/platform-tools
export PATH=${PATH}:${ANDROID_HOME}/cmdline-tools/latest/bin
export PATH=${PATH}:${HOME}/.yarn/bin
export PATH="$PATH:/usr/bin/dart"
export PATH="$HOME/.symfony/bin:$PATH"
export PATH="$HOME/.local/share/gem/ruby/3.0.0/bin:$PATH"
export PATH="$HOME/.docker/bin:$PATH"

export FZF_DEFAULT_COMMAND='fd --hidden --type f --follow --color=always --exclude .git'
export FZF_DEFAULT_OPTS="--ansi"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

export VISUAL=cursor
export EDITOR="nvim"

export CHROME_EXECUTABLE=/usr/bin/google-chrome-stable
export GPG_TTY=$(tty)

export NVM_DIR="$HOME/.nvm"