export TERM="xterm-256color"
export LANG="en_US.UTF-8"

export HISTFILE=~/.histfile
export HISTSIZE=1000
export SAVEHIST=1000

export ZPLUG_HOME=/usr/local/opt/zplug

export ANDROID_HOME=${HOME}/Android/Sdk
export JAVA_HOME="/usr/lib/jvm/java-8-openjdk/jre"
export _JAVA_AWT_WM_NONREPARENTING=1 # Fixes grey java apps
export PATH=${PATH}:${HOME}/.bin
export PATH=${PATH}:${HOME}/.local/bin
export PATH=${PATH}:${ANDROID_HOME}/emulator
export PATH=${PATH}:${ANDROID_HOME}/tools
export PATH=${PATH}:${ANDROID_HOME}/platform-tools
export PATH=${PATH}:${HOME}/.yarn/bin
export PATH=${PATH}:${JAVA_HOME}/bin:$PATH
export PATH=${PATH}:${HOME}/lib/flutter/bin
export PATH="$PATH:/usr/bin/dart"
export PATH="$HOME/.symfony/bin:$PATH"
export PATH="$HOME/.local/share/gem/ruby/3.0.0/bin:$PATH"

export FZF_DEFAULT_COMMAND='fd --hidden --type f --follow --color=always --exclude .git'
export FZF_DEFAULT_OPTS="--ansi"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

export _JAVA_OPTIONS=-Djava.io.tmpdir=/var/tmp
export VISUAL=vim
export EDITOR="$VISUAL"

export CHROME_EXECUTABLE=/usr/bin/google-chrome-stable
